default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  timeout: 5000
  database: <%= ENV["RAILS_DATABASE"] %>

development:
  <<: *default

test:
  <<: *default
  database: sike_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
